import { useEffect, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";

const checks = ["CHECKING SECURE CHANNEL", "LOADING PORTFOLIO MODULES", "ACCESS READY"];
export default function AccessGate() {
  const [visible, setVisible] = useState(true), [entering, setEntering] = useState(false), [step, setStep] = useState(0);
  useEffect(() => { const timers = checks.map((_, index) => setTimeout(() => setStep(index + 1), 440 * (index + 1))); return () => timers.forEach(clearTimeout); }, []);
  const ready = step >= checks.length;
  const enter = () => { if (!ready) return; setEntering(true); window.setTimeout(() => setVisible(false), 1180); };
  return <AnimatePresence>{visible && <motion.section className={`access-gate ${entering ? "is-entering" : ""}`} initial={{ opacity:1 }} exit={{ opacity:0, transition:{ duration:.28 } }} aria-label="Portfolio access gateway"><div className="gate-grid" /><div className="gate-shield" aria-hidden="true"><svg viewBox="0 0 320 370"><path d="M160 12 289 61v108c0 89-53 151-129 188C84 320 31 258 31 169V61L160 12Z" /><path d="M160 43 260 81v86c0 67-37 117-100 151-63-34-100-84-100-151V81l100-38Z" /><path className="shield-core" d="m111 179 31 31 70-76" /></svg></div><div className="gate-transition" aria-hidden="true"><i /><i /><b>ACCESS GRANTED</b></div><header className="gate-topbar"><span className="gate-brand">AF<span>_</span></span><span><i /> SECURE ACCESS NODE</span></header><motion.div className="gate-content" initial={{ opacity:0, y:20 }} animate={{ opacity:1, y:0 }} transition={{ duration:.6 }}><p className="gate-status"><i /> IDENTITY VERIFICATION</p><div className={`gate-scanner ${ready ? "ready" : ""}`}><i className="scanner-contact scanner-contact-a" /><i className="scanner-contact scanner-contact-b" /><div className="gate-mark">AF<span>_</span></div></div><div className="gate-checks" aria-live="polite">{checks.map((check, index) => <p className={step > index ? "complete" : step === index ? "active" : ""} key={check}><b>{step > index ? "✓" : step === index ? "•" : "○"}</b>{check}</p>)}</div><div className="gate-details"><span>LOCATION <b>MUMBAI, IN</b></span><span>ROLE <b>INFOSEC INTERN</b></span><span>CLEARANCE <b>PUBLIC</b></span></div><motion.button className="access-button" onClick={enter} disabled={!ready || entering} initial={{ opacity:0, y:8 }} animate={{ opacity:ready ? 1 : 0, y:ready ? 0 : 8 }} transition={{ duration:.3 }}>{entering ? <span>AUTHENTICATING...</span> : <span>ENTER PORTFOLIO</span>}<b>↗</b></motion.button><p className="gate-foot">PORTFOLIO ACCESS / 2026</p></motion.div></motion.section>}</AnimatePresence>;
}
