import { useState } from "react";
const answers = [
  { keys:["project","work","case study"], text:"Affan has six hands-on security projects across secure design, web testing, and IoT security. Open Projects to filter them by domain.", action:"Explore projects", href:"#projects" },
  { keys:["skill","tool","burp","nmap","wireshark","kali"], text:"Core tools include Kali Linux, Nmap, Wireshark, Burp Suite, Tenable Nessus, Bash, Python, SQL, and VMware.", action:"View skills", href:"#skills" },
  { keys:["intern","experience","dc infotech","job"], text:"Affan is currently an Information Security Intern at DC Infotech and Communication LTD in Mumbai, and previously completed a Cybersecurity Specialist internship at First Quadrant Labs.", action:"View experience", href:"#experience" },
  { keys:["contact","email","hire","connect"], text:"You can contact Affan at aaaffansayed@gmail.com or use the enquiry form in the contact section.", action:"Contact Affan", href:"#contact" },
  { keys:["resume","cv"], text:"Affan’s latest resume is available as a PDF download from the hero section.", action:"Download CV", href:"/resume.pdf" },
  { keys:["hello","who","about"], text:"I’m Affan’s portfolio assistant. I can help you find his projects, skills, experience, resume, or contact details." },
];
function respond(input) { const normalized = input.toLowerCase(); return answers.find(answer => answer.keys.some(key => normalized.includes(key))) || { text:"I can help with Affan’s projects, tools, internship experience, resume, or contact details. Try asking about one of those." }; }
export default function PortfolioAssistant() { const [open, setOpen] = useState(false), [messages, setMessages] = useState([{ from:"bot", text:"Hi — I’m Affan’s portfolio assistant. Ask about projects, skills, experience, or contact details." }]), [input, setInput] = useState(""); const send = event => { event.preventDefault(); if (!input.trim()) return; const answer = respond(input); setMessages(current => [...current, { from:"user", text:input }, { from:"bot", ...answer }]); setInput(""); }; const navigate = href => { setOpen(false); href.startsWith("/") ? location.assign(href) : location.assign(href); }; return <div className={`portfolio-ai ${open ? "open" : ""}`}><section className="ai-window" aria-label="Portfolio assistant"><header><div><i /> ASK AFFAN AI</div><button onClick={() => setOpen(false)} aria-label="Close assistant">×</button></header><div className="ai-messages">{messages.map((message, index) => <article className={message.from} key={index}><p>{message.text}</p>{message.action && <button onClick={() => navigate(message.href)}>{message.action} ↗</button>}</article>)}</div><div className="ai-suggestions"><button onClick={() => setInput("Tell me about projects")}>Projects</button><button onClick={() => setInput("What are Affan's skills?")}>Skills</button><button onClick={() => setInput("How do I contact Affan?")}>Contact</button></div><form onSubmit={send}><input value={input} onChange={event => setInput(event.target.value)} placeholder="Ask about the portfolio..." /><button type="submit" aria-label="Send question">↗</button></form><p className="ai-note">Answers are limited to verified portfolio information.</p></section><button className="ai-trigger" onClick={() => setOpen(value => !value)} aria-expanded={open}><span>✦</span>{open ? "CLOSE" : "ASK AFFAN AI"}</button></div>; }
