import { useState } from "react";
const answers = [
  { keys:["affan","yourself","introduce","introduction","who are you","who is affan"], text:"Affan Imran Sayed is an Information Security Intern from Mira Road, Mumbai. He is building practical experience in cybersecurity while strengthening his networking and ethical-hacking foundation." },
  { keys:["goal","future","career","want to become","ambition"], text:"Affan’s career direction is network security, cybersecurity, and ethical hacking. His focus is to learn deeply, gain hands-on experience, and grow into a capable security professional." },
  { keys:["zscaler","learning","learn","networking","network"], text:"Affan is currently learning Zscaler and building his networking knowledge from the core. This complements his existing work with tools such as Nmap, Wireshark, Kali Linux, and Burp Suite." },
  { keys:["dc infotech","current role","current internship","internship end","october"], text:"Affan is currently an Information Security Intern at DC Infotech and Communication LTD. The internship is planned through 21 October 2026, with a focus on learning and gaining practical experience." },
  { keys:["ethical hacking","hacking"], text:"Affan is building an ethical-hacking foundation through vulnerability assessment, web security testing, secure-system design, and cybersecurity tooling. His work is intended for authorized learning and defensive security purposes." },
  { keys:["project","work","case study"], text:"Affan has six hands-on security projects across secure design, web testing, and IoT security. Open Projects to filter them by domain.", action:"Explore projects", href:"#projects" },
  { keys:["skill","tool","burp","nmap","wireshark","kali"], text:"Core tools include Kali Linux, Nmap, Wireshark, Burp Suite, Tenable Nessus, Bash, Python, SQL, and VMware.", action:"View skills", href:"#skills" },
  { keys:["intern","experience","dc infotech","job"], text:"Affan is currently an Information Security Intern at DC Infotech and Communication LTD in Mumbai, and previously completed a Cybersecurity Specialist internship at First Quadrant Labs.", action:"View experience", href:"#experience" },
  { keys:["contact","email","hire","connect"], text:"You can contact Affan at aaaffansayed@gmail.com or use the enquiry form in the contact section.", action:"Contact Affan", href:"#contact" },
  { keys:["resume","cv"], text:"Affan’s latest resume is available as a PDF download from the hero section.", action:"Download CV", href:"/resume.pdf" },
  { keys:["hello","who","about"], text:"I’m Affan’s portfolio assistant. I can help you find his projects, skills, experience, resume, or contact details." },
];
function respond(input) { const normalized = input.toLowerCase(); return answers.find(answer => answer.keys.some(key => normalized.includes(key))) || { text:"I can help with Affan’s projects, tools, internship experience, resume, or contact details. Try asking about one of those." }; }
export default function PortfolioAssistant() { const [open, setOpen] = useState(false), [messages, setMessages] = useState([{ from:"bot", text:"Hi — I’m Cipher, Affan’s portfolio assistant. Ask about his projects, current InfoSec role, Zscaler learning, skills, or contact details." }]), [input, setInput] = useState(""); const send = event => { event.preventDefault(); if (!input.trim()) return; const answer = respond(input); setMessages(current => [...current, { from:"user", text:input }, { from:"bot", ...answer }]); setInput(""); }; const navigate = href => { setOpen(false); href.startsWith("/") ? location.assign(href) : location.assign(href); }; return <div className={`portfolio-ai ${open ? "open" : ""}`}><section className="ai-window" aria-label="Portfolio assistant"><header><div className="ai-title"><img className="ai-mascot" src="/ai-monkey.svg" alt="Cipher, Affan AI genius monkey" /><span>CIPHER <small>· AFFAN AI</small></span></div><button onClick={() => setOpen(false)} aria-label="Close assistant">×</button></header><div className="ai-messages">{messages.map((message, index) => <article className={message.from} key={index}><p>{message.text}</p>{message.action && <button onClick={() => navigate(message.href)}>{message.action} ↗</button>}</article>)}</div><div className="ai-suggestions"><button onClick={() => setInput("Tell me about Affan")}>About Affan</button><button onClick={() => setInput("What is Affan learning?")}>Learning</button><button onClick={() => setInput("Tell me about projects")}>Projects</button></div><form onSubmit={send}><input value={input} onChange={event => setInput(event.target.value)} placeholder="Ask Cipher about the portfolio..." /><button type="submit" aria-label="Send question">↗</button></form><p className="ai-note">Answers are limited to verified portfolio information.</p></section><button className="ai-trigger" onClick={() => setOpen(value => !value)} aria-expanded={open}><img className="mini-mascot" src="/ai-monkey.svg" alt="" />{open ? "CLOSE" : "ASK CIPHER"}</button></div>; }
