import { lazy, Suspense, useEffect, useMemo, useState } from "react";
import { motion } from "framer-motion";
import "./App.css";
const Background3D = lazy(() => import("./components/Background3D"));
import CustomCursor from "./components/CustomCursor";
import Navbar from "./components/Navbar";
import Terminal from "./components/Terminal";
import ProjectModal from "./components/ProjectModal";
import AccessGate from "./components/AccessGate";
import CommandPalette from "./components/CommandPalette";
import ScrollProgress from "./components/ScrollProgress";
import LiveStatus from "./components/LiveStatus";
import FocusMap from "./components/FocusMap";
import MatrixRain from "./components/MatrixRain";
import ActivityPanel from "./components/ActivityPanel";
import Toast from "./components/Toast";
import { FaGithub, FaLinkedin, FaEnvelope, FaArrowUpRightFromSquare, FaFileArrowDown } from "react-icons/fa6";

const skills = ["Python", "HTML", "CSS", "JavaScript", "MySQL", "SQL", "Kali Linux", "Nmap", "Wireshark", "Burp Suite", "Tenable Nessus", "Bash", "VMware", "Packet Tracer"];
const projects = [
  ["01", "Secure Remote Access Solution", "A defense-in-depth remote access design built to protect corporate resources for distributed teams.", "Designed a secure access model that emphasizes encrypted communication, strong identity verification, and access controls for employees outside the corporate network.", ["VPN", "MFA", "RBAC", "Network Security"], ["Confidentiality", "Authentication", "Least privilege"], "Reduce remote-work exposure while keeping access straightforward for legitimate users."],
  ["02", "Secure Password Manager", "A secure credential-management concept with encryption, MFA, role-based access, and encrypted backups.", "Developed a password-management system design focused on credentials at rest and in transit, paired with usability, administrative controls, and recovery planning.", ["Encryption", "MFA", "RBAC", "Secure Backups"], ["Access control", "Key management", "Data protection"], "Provide secure, usable handling of sensitive credentials."],
  ["03", "Secure Email Communication", "A secure email approach for sensitive organizational data and trusted communications.", "Implemented a security-first email communication model concentrating on confidentiality, integrity, and authentication for sensitive messages.", ["Email Security", "Encryption", "Digital Signatures"], ["Confidentiality", "Integrity", "Authentication"], "Improve trust and data protection in organizational email workflows."],
  ["04", "Host Header Injection Testing", "Web application testing to identify and validate server-side Host header vulnerabilities.", "Used Burp Suite to intercept HTTP requests, manipulate Host headers, and observe server behavior for vulnerable trust assumptions.", ["Burp Suite", "HTTP", "Web Testing"], ["Input validation", "Server-side trust", "Attack surface"], "Identify and communicate risk from improper Host header handling."],
  ["05", "Open Redirection Testing", "Security testing of redirect behavior to validate external navigation risks.", "Assessed redirect parameters and security headers to identify open redirection behavior, then validated the risk through controlled Burp Suite testing.", ["Burp Suite", "HTTP Headers", "Web Security"], ["Input validation", "Phishing risk", "Secure redirects"], "Prevent attackers using trusted domains to redirect users to unsafe destinations."],
  ["06", "IoT Smart Home Security", "A layered IoT security framework for protecting connected smart-home devices.", "Developed a comprehensive security framework considering device protection, network boundaries, privacy, and reliability in a smart-home environment.", ["IoT", "Network Segmentation", "Device Security"], ["Privacy", "Defense in depth", "Risk assessment"], "Strengthen the safety and resilience of connected home ecosystems."]
].map(([num, title, summary, detail, technologies, concepts, objective], index) => ({ num, title, summary, detail, technologies, concepts, objective, category: index === 5 ? "IoT Security" : index > 2 ? "Web Security" : "Secure Design", outcome: ["Access hardened", "Credentials protected", "Communication secured", "Server trust tested", "Phishing risk validated", "Devices safeguarded"][index] }));
const reveal = { hidden: { opacity: 0, y: 28 }, visible: { opacity: 1, y: 0, transition: { duration: .55 } } };
function Reveal({ children }) { return <motion.div variants={reveal} initial="hidden" whileInView="visible" viewport={{ once: true, amount: .16 }}>{children}</motion.div>; }

export default function App() {
  const [selectedProject, setSelectedProject] = useState(null), [filter, setFilter] = useState("All"), [theme, setTheme] = useState(() => localStorage.getItem("portfolio-theme") || (matchMedia("(prefers-color-scheme: light)").matches ? "light" : "dark")), [performanceMode, setPerformanceMode] = useState(() => localStorage.getItem("portfolio-performance") === "on");
  const filters = ["All", "Secure Design", "Web Security", "IoT Security"];
  const visibleProjects = useMemo(() => filter === "All" ? projects : projects.filter(project => project.category === filter), [filter]);
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem("portfolio-theme", theme); }, [theme]);
  useEffect(() => { document.body.classList.toggle("performance-mode", performanceMode); localStorage.setItem("portfolio-performance", performanceMode ? "on" : "off"); }, [performanceMode]);
  useEffect(() => { const projectId = new URLSearchParams(location.search).get("project"); if (projectId) setSelectedProject(projects.find(project => project.num === projectId) || null); }, []);
  const openProject = project => { setSelectedProject(project); history.replaceState(null, "", `?project=${project.num}#projects`); };
  const closeProject = () => { setSelectedProject(null); history.replaceState(null, "", "#projects"); };
  return <><CustomCursor /><AccessGate /><ScrollProgress /><CommandPalette /><MatrixRain /><Suspense fallback={<div className="three-bg" />}><Background3D /></Suspense><Navbar theme={theme} onToggleTheme={() => setTheme(theme === "dark" ? "light" : "dark")} performanceMode={performanceMode} onTogglePerformance={() => setPerformanceMode(!performanceMode)} /><main>
    <section className="hero" id="home"><div className="eyebrow">● AVAILABLE FOR OPPORTUNITIES</div><LiveStatus /><p className="hello">HELLO, I'M</p><h1>AFFAN <span>SAYED.</span></h1><p className="hero-role">INFORMATION SECURITY INTERN <b>·</b> CYBERSECURITY ENTHUSIAST</p><div className="hero-bottom"><p>Cybersecurity enthusiast with a foundation in ethical hacking, network security, vulnerability assessment, and penetration testing.</p><div className="hero-actions"><a href="#projects" className="btn primary">Explore Projects <FaArrowUpRightFromSquare /></a><a href="/resume.pdf" download className="btn ghost"><FaFileArrowDown /> Download CV</a></div></div><div className="scroll-hint">SCROLL TO EXPLORE ↓</div></section>
    <section className="section about" id="about"><Reveal><div className="section-label">01 / ABOUT</div><div className="section-grid"><h2>Building a safer<br /><span>digital world.</span></h2><div className="about-copy"><p>I'm a motivated and detail-oriented cybersecurity enthusiast with a strong foundation in ethical hacking, network security, and penetration testing.</p><p>I enjoy identifying vulnerabilities, assessing security risks, and continuously learning new technologies to strengthen cybersecurity defenses.</p><div className="stats"><div><strong>01+</strong><span>Year Internship Experience</span></div><div><strong>06</strong><span>Security Projects</span></div><div><strong>14+</strong><span>Technical Skills</span></div></div></div></div></Reveal></section>
    <section className="section terminal-section" id="terminal"><Reveal><div className="section-label">02 / SYSTEM STATUS</div><Terminal /></Reveal></section>
    <section className="section" id="skills"><Reveal><div className="section-label">03 / TECHNICAL SKILLS</div><h2 className="section-title">Tools I use to <span>secure.</span></h2><div className="skills-cloud">{skills.map((skill, i) => <motion.div className="skill" key={skill} initial={{ opacity: 0, scale: .92 }} whileInView={{ opacity: 1, scale: 1 }} viewport={{ once: true }} transition={{ delay: Math.min(i * .045, .45) }}><span>{String(i + 1).padStart(2, "0")}</span>{skill}</motion.div>)}</div><FocusMap /></Reveal></section>
    <section className="section experience" id="experience"><Reveal><div className="section-label">04 / EXPERIENCE</div><div className="experience-list"><div className="experience-card current-role"><div className="experience-top"><span>21 JUL 2026 — PRESENT</span><span>MUMBAI, INDIA</span></div><h2>Information Security <span>Intern</span></h2><h3>DC Infotech and Communication LTD</h3><p>Building practical industry experience in information security while supporting the security needs of a technology and communications organization.</p></div><div className="experience-card"><div className="experience-top"><span>JUN 2025 — JAN 2026</span><span>MUMBAI, INDIA</span></div><h2>Cybersecurity Specialist <span>Intern</span></h2><h3>First Quadrant Labs</h3><p>Contributed to multiple cybersecurity projects involving secure remote access, password security, secure communication, web vulnerability testing, and IoT security.</p></div></div><ActivityPanel /></Reveal></section>
    <section className="section" id="projects"><Reveal><div className="section-label">05 / FEATURED WORK</div><h2 className="section-title">Security projects.<br /><span>Real-world thinking.</span></h2><div className="project-metrics"><span><b>06</b> CASE STUDIES</span><span><b>03</b> SECURITY DOMAINS</span><span><b>100%</b> HANDS-ON</span></div><div className="project-filters" aria-label="Filter projects">{filters.map(item => <button className={filter === item ? "selected" : ""} onClick={() => setFilter(item)} key={item}>{item}</button>)}</div><div className="projects-grid">{visibleProjects.map((project, i) => <motion.button className="project-card" key={project.num} onClick={() => openProject(project)} initial={{ opacity: 0, y: 25 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: Math.min(i * .08, .4) }}><div className="project-num">{project.num} / {project.category}</div><h3>{project.title}</h3><p>{project.summary}</p><strong className="project-outcome">{project.outcome}</strong><div className="project-line" /><span className="project-arrow">↗</span><span className="project-cta">Open case study</span></motion.button>)}</div></Reveal></section>
    <section className="section education" id="education"><Reveal><div className="section-label">06 / EDUCATION & LEARNING</div><div className="timeline"><div><span>2025 — 2026</span><h3>Bachelor of Commerce (BCom)</h3><p>Shree Ram College · Mumbai, India</p></div><div><span>2024 — 2025</span><h3>Cyber Security & Ethical Hacking</h3><p>Boston Institute of Analytics · Mumbai, India</p></div><div><span>2023 — 2024</span><h3>Master in Data Software Engineering</h3><p>ITVedant · Mumbai, Maharashtra</p></div></div></Reveal></section>
    <section className="contact-section" id="contact"><Reveal><div className="section-label">07 / CONTACT</div><p className="contact-small">HAVE AN OPPORTUNITY OR WANT TO CONNECT?</p><h2>Let's make something<br /><span>secure together.</span></h2><div className="contact-grid"><div><div className="secure-mail"><div className="secure-mail-status"><i /> CHANNEL READY <span>MAIL / ENQUIRY</span></div><h3>Secure mail<br />channel.</h3><p>For opportunities, collaborations, or professional conversations, contact me directly. Please do not send passwords, credentials, or confidential security findings through this public form.</p><a className="email-link" href="mailto:aaaffansayed@gmail.com?subject=Portfolio%20enquiry%20for%20Affan%20Sayed">aaaffansayed@gmail.com ↗</a></div><div className="contact-links"><a href="https://github.com/sayedaffan1" target="_blank" rel="noreferrer"><FaGithub /> GitHub</a><a href="https://www.linkedin.com/in/affan-sayyed-21b968256/" target="_blank" rel="noreferrer"><FaLinkedin /> LinkedIn</a><a href="mailto:aaaffansayed@gmail.com"><FaEnvelope /> Email</a></div></div><form className="contact-form" action="https://formsubmit.co/aaaffansayed@gmail.com" method="POST"><div className="form-head"><span>PUBLIC ENQUIRY FORM</span><i>SPAM PROTECTED</i></div><input type="hidden" name="_subject" value="New portfolio enquiry" /><input type="hidden" name="_next" value="https://affansayed.vercel.app/#contact" /><input className="honeypot" type="text" name="_honey" tabIndex="-1" autoComplete="off" /><label>Name<input name="name" required placeholder="Your name" /></label><label>Email<input name="email" type="email" required placeholder="you@example.com" /></label><label>Message<textarea name="message" required rows="4" placeholder="Tell me about the opportunity..." /></label><button className="btn primary" type="submit">Send message <FaArrowUpRightFromSquare /></button></form></div></Reveal></section>
  </main><footer>© 2026 AFFAN SAYED · CYBERSECURITY PORTFOLIO</footer><ProjectModal project={selectedProject} onClose={closeProject} /><Toast /></>;
}
